### PR TITLE
Allow passing of a new variable aws_sns_topic_arn and not create an SNS topic

### LINKED ISSUE #34: Allow to not generate a new SNS topic
## Describe the Feature
Allow passing of a new variable `aws_sns_topic_arn` and do not create yet another SNS topic.

## Use Case

We have a lot of SNS topics.  We would like to not have another one.

### PR DESCRIPTION
**Pull request by bogdanbarna**
## what
* Add variable `aws_sns_topic_arn`
* This extends the current module, allowing users to pass the ARN of an existing SNS topic
* The `locals` block in main.tf handles the logic of whether to create aws_sns_topic.default.

## why
* Some teams use one SNS topic for multiple CloudWatch alarms

## references
Closes #34.

### CODE REVIEW

**Review by nitrocode — APPROVED** [review]

**Review by nitrocode — CHANGES_REQUESTED** [review]
The auto format is failing.

**Comment by GregoryVds** [comment]
Hi
I am interested in getting this merged as well.

@nitrocode it seems that the autoformat error was a transient one?
`Error: We are currently unable to download the log. Please try again later.`

Can we trigger another build and hopefully get this merged in?

**Comment by bogdanbarna** [comment]
Hi. Sorry, totally forgot about this one. I'll take a look at the formatting issue later today and hopefully push a commit for it. Thanks.

**Comment by bogdanbarna** [comment]
Hi. I apologize for the late reply. I'm not able to have this running again and also don't work with ClassEDU (where the fork was created) anymore.
Regards.

**Pull request closed without merging**
