### PR TITLE
Support KMS master key id to encrypt SNS topic

### PR DESCRIPTION
**Pull request by msrdjan**
## what

Add `kms_master_key_id` variable to be set for the `aws_sns_topic` resource (default is `null`, usually set to `alias/aws/sns` for AWS managed AWS KMS for Amazon SNS).

## why

To protect the contents of messages in Amazon SNS topics using keys managed in AWS Key Management Service (AWS KMS).

Resolves [Topic does not have encryption enabled `AVD-AWS-0095`](https://avd.aquasec.com/misconfig/aws/sns/avd-aws-0095/#unencrypted-sns-topic).

## references

- [AWS SNS Server-side Encryption](https://docs.aws.amazon.com/sns/latest/dg/sns-server-side-encryption.html)
- [Topic does not have encryption enabled  `AVD-AWS-0095`](https://avd.aquasec.com/misconfig/aws/sns/avd-aws-0095/#unencrypted-sns-topic)

### CODE REVIEW

**Comment by msrdjan** [comment]
I noticed that I've missed to run `make init` and `make readme` to update the docs. Sorry!

I've done that now and pushed changes to trigger the tests again.

**Comment by msrdjan** [comment]
Terratest was failing in `examples/complete/main.tf`, with error:

```
Error: creating RDS Event Subscription (eg-test-rds-alarms-yk7ds2-rds-event-sub): operation error RDS: CreateEventSubscription, https response error StatusCode: 404, RequestID: f83ad2f7-e073-4487-9580-3f38d6f3ae65, SourceNotFound: Could not find source :db-YK56SLLLPFEVYEW2XADSJ7RBZY

  on ../../main.tf line 30, in resource "aws_db_event_subscription" "default":
  30: resource "aws_db_event_subscription" "default" {

}
```

most likely because of slower database resource creation.

In my code, I have fixed it by adding `depends_on`.

**Review by hans-d — APPROVED** [review]

**Pull request closed without merging**
