### PR TITLE
Add unicity to alert names using instance ID (#5)

### LINKED ISSUE #5: alarm names should be unique
terraform doesn't complain about the conflict, but the alarms will constantly have their dimension overwritten with every deploy if the names aren't unique.

### PR DESCRIPTION
**Pull request by rebelthor**
This PR resolves #5 by using the instance ID in the alert names for unicity.

### CODE REVIEW

**Review by osterman — CHANGES_REQUESTED** [review]
You're totally correct in submitting this PR and this needs to be addressed. Unfortunately, I need to ask that we use the `terraform-null-label` module (or `terraform-terraform-label` module - your pick) to generate all the labels for consistency with all of our other modules.

**Comment by aknysh** [comment]
@rebelthor  thanks, any update on this?

**Comment by kieferrj** [comment]
Nah, merge it as is. Null labels obscure quick identifiability. Introduci ambiguity into what could otherwise be "At a glance" ready data is a huge turnoff. It doesn't add any value beyond just being unique, and actually makes the result worse outside of that.

**Comment by caleb15** [comment]
@osterman can the null label change be left for a seperate PR? This PR just fixes the alert names and it would be good for this to be merged in sooner rather than later so other people don't run into the #5 bug

**Comment by joe-niland** [comment]
Superseded by #20

**Pull request closed without merging**
