### PR TITLE
Remove strings from variable types

### PR DESCRIPTION
**Pull request by kevcube**
## what
* Remove quotes from variable types

## why
* Broken in terraform 0.15

### CODE REVIEW

**Comment by kevcube** [comment]
@joe-niland can you plz re-exec tests 😄

**Comment by kevcube** [comment]
@joe-niland once more please! 😄

**Comment by kevcube** [comment]
@joe-niland looks like they didn't execute

**Comment by joe-niland** [comment]
Ah sorry @kevcube, just realised this repo is out of date with respect to automation. We'll have to get that fixed.

**Comment by joe-niland** [comment]
@kevcube I added the tests and other automation so please check this one again and we'll go from there.

**Comment by kevcube** [comment]
😞 dang lol

**Comment by joe-niland** [comment]
@kevcube sorry about that :) the upgrade procedure we used included this change

**Pull request closed without merging**
